# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '37 22 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Check secrets
        run: |
          if [[ -z "${{ secrets.TWITTER_USERNAME }}" ]]; then
            echo "Secret TWITTER_USERNAME is not set."
          else
            echo "Secret TWITTER_USERNAME is set."
          fi
          if [[ -z "${{ secrets.TWITTER_PASSWORD }}" ]]; then
            echo "Secret TWITTER_PASSWORD is not set."
          else
            echo "Secret TWITTER_PASSWORD is set."
          fi
      - name: Yarn
        run: npm install -g pnpm
      - name: Install
        run: pnpm install
      - name: Test
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: pnpm test
      - name: Build
        run: pnpm build
