name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Yarn
        run: npm install -g pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      # - name: Publish
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: pnpm publish --access public
